// Rateriet – UI-tekster (norsk + engelsk). Fagtermer (noter/akkorder) holdes uoversatt.
export const STRINGS = {
  no: {
    tagline: "Oppdag, vurder og sammenlign parfymer — finn duften som passer deg, og dupene verdt å kjenne til.",
    discover: "Oppdag",
    toplists: "Topplister",
    account: "Konto",
    signin: "Logg inn",
    searchPlaceholder: "🔍 Søk parfyme, hus eller note…",
    all: "Alle",
    allPrices: "Alle priser",
    perfumes: "parfymer",
    filterByScent: "Filtrer på duft",
    filters: "Filtre",
    showAll: "Vis alle",
    showLess: "Vis færre",
    clearFilters: "Nullstill",
    noResults: "Ingen treff. Prøv å justere søk eller filtre.",
    topCta: "✨ Savner du en parfyme? Foreslå den – vi er takknemlige for hjelpen.",
    missingCta: "Fant du ikke parfymen din?",
    missingCtaSub: "Vi bygger katalogen sammen med dere – og er veldig takknemlige for hjelpen. Foreslå en parfyme du savner, så legger vi den til.",
    missingCtaBtn: "✨ Foreslå en parfyme",
    noResultsCta: "Savner du denne? Foreslå den – vi legger den gjerne til.",
    notRated: "Ikke vurdert",
    new: "ny",
    votes: "stemmer",
    vote: "stemme",
    // detail
    back: "← Tilbake",
    top: "Topp",
    heart: "Hjerte",
    base: "Base",
    community: "Fellesskap",
    longevity: "Holdbarhet",
    sillage: "Duftspor",
    longevityHelp: "hvor lenge duften varer på huden",
    sillageHelp: "hvor mye folk rundt deg merker duften",
    dupesOf: "🔁 Duper av",
    dupesSub: "Rimeligere alternativer som lukter likt",
    rateThis: "Vurder denne parfymen",
    yourRating: "Din vurdering (vurder igjen for å oppdatere)",
    optionalReview: "Valgfri omtale…",
    submitRating: "Send vurdering",
    saving: "Lagrer…",
    reviews: "Omtaler",
    // toplists
    top10: "Topp 10 akkurat nå",
    top10sub: "Rangert etter fellesskapets vurderinger. Sammenlign to grupper side om side.",
    noRatingsGroup: "Ingen vurderinger ennå for denne gruppen.",
    // account
    createAccount: "Opprett konto",
    username: "Brukernavn",
    email: "E-post",
    password: "Passord",
    ageForLists: "Alder (for topplister)",
    age: "Alder",
    signup: "Registrer deg",
    newHere: "Ny her? Opprett konto",
    haveAccount: "Har du konto? Logg inn",
    yourDemographics: "Din demografi",
    demographicsSub: "Brukes til de demografiske topplistene",
    save: "Lagre",
    saved: "Lagret!",
    signout: "Logg ut",
    admin: "⚙️ Admin",
    inDatabase: "i databasen",
    seedBtn: "Last inn parfymer fra seedData.js",
    // legg til parfyme (brukerinnsending)
    addPerfume: "+ Foreslå en parfyme",
    addPerfumeTitle: "Foreslå en parfyme",
    addPerfumeSub: "Savner du en parfyme? Foreslå den, så legger vi den til etter en sjekk.",
    fldName: "Navn",
    fldHouse: "Hus / merke",
    fldNote: "Noter eller kommentar (valgfritt)",
    submitSuggestion: "Send forslag",
    suggestionThanks: "Takk! Forslaget er sendt til godkjenning.",
    signinToSuggest: "Logg inn for å foreslå en parfyme.",
    pendingQueue: "Forslag til godkjenning",
    noPending: "Ingen forslag akkurat nå.",
    by: "av",
    // genders / prices (for filters)
    gender_All: "Alle", gender_Masculine: "♂ Maskulin", gender_Feminine: "♀ Feminin", gender_Unisex: "⚥ Unisex",
    price_budget: "💸 Budsjett", price_mid: "💵 Mellom", price_luxury: "💎 Luksus",
    // alerts
    pickStars: "Velg en stjernerangering først.",
    signinToRate: "Logg inn for å vurdere.",
    thanksRating: "Takk for vurderingen!",
    loading: "Laster Rateriet…",
  },
  en: {
    tagline: "Discover, rate & compare perfumes — find the scent that's right for you, and the dupes worth knowing about.",
    discover: "Discover",
    toplists: "Top Lists",
    account: "Account",
    signin: "Sign in",
    searchPlaceholder: "🔍 Search perfume, house or note…",
    all: "All",
    allPrices: "All prices",
    perfumes: "perfumes",
    filterByScent: "Filter by scent",
    filters: "Filters",
    showAll: "Show all",
    showLess: "Show less",
    clearFilters: "Clear",
    noResults: "No matches. Try adjusting search or filters.",
    topCta: "✨ Missing a perfume? Suggest it – we're grateful for the help.",
    missingCta: "Didn't find your perfume?",
    missingCtaSub: "We build the catalogue together with you – and we're truly grateful for the help. Suggest a perfume you're missing and we'll add it.",
    missingCtaBtn: "✨ Suggest a perfume",
    noResultsCta: "Missing this one? Suggest it – we'd love to add it.",
    notRated: "Not rated",
    new: "new",
    votes: "votes",
    vote: "vote",
    back: "← Back",
    top: "Top",
    heart: "Heart",
    base: "Base",
    community: "Community",
    longevity: "Longevity",
    sillage: "Projection",
    longevityHelp: "how long the scent lasts on skin",
    sillageHelp: "how much people around you notice it",
    dupesOf: "🔁 Dupes of",
    dupesSub: "Cheaper alternatives that smell similar",
    rateThis: "Rate this perfume",
    yourRating: "Your rating (rate again to update)",
    optionalReview: "Optional review…",
    submitRating: "Submit rating",
    saving: "Saving…",
    reviews: "Reviews",
    top10: "Top 10 right now",
    top10sub: "Ranked by community ratings. Compare two groups side by side.",
    noRatingsGroup: "No ratings yet for this group.",
    createAccount: "Create account",
    username: "Username",
    email: "Email",
    password: "Password",
    ageForLists: "Age (for top lists)",
    age: "Age",
    signup: "Sign up",
    newHere: "New here? Create account",
    haveAccount: "Have an account? Sign in",
    yourDemographics: "Your demographics",
    demographicsSub: "Used for the demographic top lists",
    save: "Save",
    saved: "Saved!",
    signout: "Sign out",
    admin: "⚙️ Admin",
    inDatabase: "in database",
    seedBtn: "Seed perfumes from seedData.js",
    addPerfume: "+ Suggest a perfume",
    addPerfumeTitle: "Suggest a perfume",
    addPerfumeSub: "Missing a perfume? Suggest it and we'll add it after a quick check.",
    fldName: "Name",
    fldHouse: "House / brand",
    fldNote: "Notes or comment (optional)",
    submitSuggestion: "Send suggestion",
    suggestionThanks: "Thanks! Your suggestion was sent for approval.",
    signinToSuggest: "Sign in to suggest a perfume.",
    pendingQueue: "Suggestions to approve",
    noPending: "No suggestions right now.",
    by: "by",
    gender_All: "All", gender_Masculine: "♂ Masculine", gender_Feminine: "♀ Feminine", gender_Unisex: "⚥ Unisex",
    price_budget: "💸 Budget", price_mid: "💵 Mid", price_luxury: "💎 Luxury",
    pickStars: "Pick a star rating first.",
    signinToRate: "Sign in to rate.",
    thanksRating: "Thanks for rating!",
    loading: "Loading Rateriet…",
  },
};
